#
# Module  W90 with GNU MKL
#

set     name        wannier
set     version     dev_nix2.3_ompi
set     root        REPLACEDIR

set     description "wannier90 dev vers3.1 compiled with gnu and openmpi"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of triqs can be loaded at a time
conflict $name intel/mpi intel/compiler


module          load    MODULES

prepend-path    PATH               $root/bin
prepend-path    PATH               $root
prepend-path    LIBRARY_PATH       $root/lib
prepend-path    LD_LIBRARY_PATH    $root/lib

setenv          WANNIER90_BASE                       $root
setenv          WANNIER90_ROOT                       $root
setenv          WANNIER90_VERSION                    $version
