#
# Module  Quantum Espresso with W90 with GNU MKL  
#

set     name        ftps_itensor
set     version     3_unstable_ompi_mkl
set     root        REPLACEDIR 

set     description "FTPS itensor on top of triqs 3" 

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of triqs can be loaded at a time
conflict $name intel/mpi intel/compiler


module          load    MODULES

setenv          ITENSOR_ROOT     $root/installation           
setenv          MKL_NUM_THREADS  1
