#
# Modul triqs unstable compiled with intel oneAPI
#

set     name        triqs 
set     version     beyondDFT_nix2_gnu
set     root        REPLACEDIR 

set     description "beyondDFT package" 

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}


module          load    MODULES

setenv CC       gcc
setenv CXX      g++ 
setenv CXXFLAGS "-Wno-register -march=broadwell"
setenv FC       gfortran
setenv BLA_VENDOR Intel10_64_dyn

setenv          TBLIS_ROOT          $root
setenv          slate_ROOT          $root
setenv          INSTALLDIR          $root
setenv          MKL_NUM_THREADS     1
setenv          MKL_INTERFACE_LAYER GNU,LP64
setenv          MKL_THREADING_LAYER SEQUENTIAL
setenv          UCX_LOG_LEVEL       error

prepend-path    PATH                $root/bin
prepend-path    CPLUS_INCLUDE_PATH  $root/include
prepend-path    LIBRARY_PATH        $root/lib
prepend-path    LIBRARY_PATH        $root/lib64
prepend-path    LD_LIBRARY_PATH     $root/lib
prepend-path    LD_LIBRARY_PATH     $root/lib64
prepend-path    PYTHONPATH          $root/lib/python3.10/site-packages


