#
# Module  W90 with GNU MKL  
#

set     name        wannier
set     version     3.1_gnu_ompi
set     root        REPLACEDIR 

set     description "wannier90 vers3.1 compiled with gnu and openmpi"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of triqs can be loaded at a time
conflict $name intel/mpi intel/compiler


module          load    MODULE 

prepend-path    PATH    $root/bin
