#
# Module  Vasp linked against W90 with GNU MKL  
#

set     name        vasp
set     version     6.4.1_nix2.1_gnu_ompi
set     root        REPLACEDIR

set     description "Vasp 6.4.1 + wannier90 dev compiled with gnu and openmpi"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of triqs can be loaded at a time
conflict $name intel/mpi intel/compiler


module          load    MODULES
prepend-path    PATH    $root/bin
setenv          MKL_NUM_THREADS     1
setenv          OMP_NUM_THREADS     1
