#
# Module Elk 6.2.8 triqs interfaced version with GNU MKL  
#

set     name        vasp
set     version     6.2.8_ompi
set     root        REPLACEDIR

set     description "Elk 6.2.8 compiled with gnu and openmpi 4"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of elk can be loaded at a time
conflict $name intel/mpi intel/compiler


module          load    MODULES
prepend-path    PATH    $root/bin
