#
# Module  Quantum Espresso with W90 with GNU MKL  
#

set     name        qe
set     version     7.2_gnu_ompi_respack
set     root        REPLACEDIR 

set     description "Quantum Espresso ver 7.2 including wannier90, RESPACK, and unfold-x compiled with MODULES"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of triqs can be loaded at a time
conflict $name intel/mpi intel/compiler


module          load    MODULES
prepend-path    PATH    $root/bin
prepend-path    CPLUS_INCLUDE_PATH  $root/include
prepend-path    LIBRARY_PATH        $root/lib64

setenv          MKL_NUM_THREADS     1
setenv          OMP_NUM_THREADS     1
setenv CC       gcc
setenv CXX      g++
setenv CXXFLAGS "-stdlib=libc++ -Wno-register -march=broadwell"
setenv FC       gfortran
