#
# Module: abinit with openmpi
#

set name abinit
set version 8.10.3_nix2_gnu_ompi
set     root        REPLACEDIR

set     description "abinit ver 8.10.3 compiled with MODULES"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

conflict $name intel/mpi intel/compiler

module          load    MODULES
prepend-path    PATH                            $root/bin
prepend-path    LD_LIBRARY_PATH                 $root/lib

setenv          ABINIT_BASE                       $root
setenv          ABINIT_VERSION                    $version
