#
# Module  Quantum Espresso with W90 with GNU MKL  
#

set     name        qe
set     version     6.6_gnu_ompi
set     root        REPLACEDIR 

set     description "Quantum Espresso ver 6.6 including wannier90 vers3.1 compiled with gnu and openmpi"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of triqs can be loaded at a time
conflict $name intel/mpi intel/compiler


module          load    gcc/7.4.0 openmpi4/4.0.5 intel/mkl/2019-3  wannier90/3.1_gnu_ompi/module
prepend-path    PATH    $root/qe/bin
