#
# Module  Vasp 
#

set     name        vasp
set     version     6.1.2_impi
set     root        REPLACEDIR

set     description "Vasp 6.1.2 compiled with Intel MPI"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of triqs can be loaded at a time
conflict $name gcc openmpi2 openmpi4


module          load    MODULES
prepend-path    PATH    $root/bin
