#
# Module  Vasp linked against W90 with GNU MKL  
#

set     name        vasp
set     version     6.8.4_ompi
set     root        REPLACEDIR

set     description "Elk 6.8.4 compiled with gnu and openmpi 4"

module-whatis   "$description"

proc ModulesHelp { } {
    global description url version git_hash
    puts stderr "Description: $description"
    puts stderr "Version:     $version"
}

# Only one version of triqs can be loaded at a time
conflict $name intel/mpi intel/compiler


module          load    MODULES
prepend-path    PATH    $root/bin
